### ISSUE TITLE
provide some basic JS renderers/viewers for different types of files

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-webui#4]
E.g. for markdown (most pressing imho) we could may be use smth like http://strapdownjs.com , there is a number of viewers for niftis.

@mih has lots of experience from studyforrest already, so could advise ;)

**Comment by yarikoptic** [comment]
some renderers would be external services, some would be local (e.g. nifti renderers etc).  Some summary on initial set of external services: https://github.com/dandi/dandiarchive/wiki/WiP:-dump-of-thoughts-on-%22services-registry%22 .

edit dump of ideas:
- some services will be external, so a new page/tab would open
- but some would have renderer(s) like markdown one , and we assign default renderer so going to a file would open a page with the file rendered
- within "renderer" view provide a menu with all those alternative renderers or services or "view raw"

@soichih -- would you be so kind to remind me which component you used for the context menu pop up.

**Comment by soichih** [comment]
I just hook "contextmenu" event and show custom menu 

```
const noContext = document.getElementById('noContextMenu');
noContext.addEventListener('contextmenu', e => {
  e.preventDefault();
  //show context menu div element
});
```

You can just draw a menu (just a div with menu init - position: fixed to the location of the cursor) You then have to hide the menu once user select an item / hit-ESC / click outside menu, etc.. 

If you don't want to implement all that, there are tons of "context menu" components for any UI frameworks like https://github.com/vuejs/awesome-vue#context-menu.  Are you using any UI framework? Or are you using plain JS/jquery?

**Comment by yarikoptic** [comment]
> If you don't want to implement all that, there are tons of "context menu" components for any UI frameworks like https://github.com/vuejs/awesome-vue#context-menu. Are you using any UI framework? Or are you using plain JS/jquery?

no UI framework so far to keep it as lean as possible, so just some jquery + jquery.dataTables (https://github.com/datalad/datalad-deprecated/tree/master/datalad_deprecated/resources/website/assets/js) -- the idea is to have this framework lean so any datalad user could easily deploy it (`datalad create-sibling --ui true` does that).

BTW -- we should think about how to "integrate" with brainlife.io -- could be one of the external services ("Import to brainlife.io" or "View on brainlife.io" or alike item(s) )

**Comment by soichih** [comment]
I *love* doing it simple / lean !! :) If you want to stick with jquery, maybe you can try this then? https://swisnl.github.io/jQuery-contextMenu/demo.html

Pretty much any modern UI framework requires at least webpack or more complex tooling to get it built..  But once it's built, deployment is still as simple as exposing the content of /dist (or whatever..) via a web browser. So from that point of view, it shouldn't matter if you use something like vue or not.

**Comment by yarikoptic** [comment]
accomplished by @dereklu888 in deprecated/pull/27 (me is yet to migrate code to this repo/extension)
