### ISSUE TITLE
set title to the breadcrumbs path

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-webui#7]
just now noticed that browser history just has "DataLad Repository".  0byte entropy ;) not good. just a matter of setting a title for the page. 
Should just be what we provide in breadcrumb'ed path.

**Comment by dereklu888** [comment]
Just coded this up, but the title at times gets rather long for deeper paths. Should I instead just have it be the last crumb? like: "Datalad Repository: lastfoldername" instead of "Datalad Repository: firstfolder/secondfolder/lastfoldername"?

**Comment by yarikoptic** [comment]
closed by a PR in datalad-deprecated
